### PR TITLE
Adding action for cart events and logic to keep track of quantities

### PR DESCRIPTION
**Pull request by trisberg**

### CODE REVIEW

**Comment by markfisher** [comment]
The original idea is that the "quantity" was the actual value, not a delta... otherwise things get tricky if you interact with a cart from multiple devices. I was thinking along the same lines as `kubectl scale ... --replicas 5` as opposed to scaling with a +/- value.

**Comment by trisberg** [comment]
I see, so the cart-events should have the actual numbers in the cart, just hope they arrive in the correct sequence

**Comment by markfisher** [comment]
regarding order, we should at a minimum add a timestamp to the event

I also added a comment on the corresponding storefront issue

**Comment by markfisher** [comment]
also, this provides a good exemplar for strict-ordering within a partition (e.g. with partition key being userid)

**Pull request closed without merging**
